export default [
  {value: "Genesis", label: "Genesis", numberOfChapters: 50},
  {value: "Exodus", label: "Exodus", numberOfChapters: 40},
  {value: "Leviticus", label: "Leviticus",  numberOfChapters: 27},
  {value: "Numbers", label: "Numbers",  numberOfChapters: 36},
  {value: "Deuteronomy", label: "Deuteronomy",  numberOfChapters: 34},
  {value: "Joshua", label: "Joshua",  numberOfChapters: 24},
  {value: "Judges", label: "Judges",  numberOfChapters: 21},
  {value: "Ruth", label: "Ruth",  numberOfChapters: 4},
  {value: "1 Samuel", label: "1 Samuel",  numberOfChapters: 31},
  {value: "2 Samuel", label: "2 Samuel",  numberOfChapters: 24},
  {value: "1 Kings", label: "1 Kings",  numberOfChapters: 22},
  {value: "2 Kings", label: "2 Kings",  numberOfChapters: 25},
  {value: "1 Chronicles", label: "1 Chronicles",  numberOfChapters: 29},
  {value: "2 Chronicles", label: "2 Chronicles",  numberOfChapters: 36},
  {value: "Ezra", label: "Ezra",  numberOfChapters: 10},
  {value: "Nehemiah", label: "Nehemiah",  numberOfChapters: 13},
  {value: "Esther", label: "Esther",  numberOfChapters: 10},
  {value: "Job", label: "Job",  numberOfChapters: 42},
  {value: "Psalms", label: "Psalms",  numberOfChapters: 150},
  {value: "Proverbs", label: "Proverbs",  numberOfChapters: 31},
  {value: "Ecclesiastes", label: "Ecclesiastes",  numberOfChapters: 12},
  {value: "Song of Solomon", label: "Song of Solomon",  numberOfChapters: 8},
  {value: "Isaiah", label: "Isaiah",  numberOfChapters: 66},
  {value: "Jeremiah", label: "Jeremiah",  numberOfChapters: 52},
  {value: "Lamentations", label: "Lamentations",  numberOfChapters: 5},
  {value: "Ezekiel", label: "Ezekiel",  numberOfChapters: 48},
  {value: "Daniel", label: "Daniel",  numberOfChapters: 12},
  {value: "Hosea", label: "Hosea",  numberOfChapters: 14},
  {value: "Joel", label: "Joel",  numberOfChapters: 3},
  {value: "Amos", label: "Amos",  numberOfChapters: 9},
  {value: "Obadiah", label: "Obadiah",  numberOfChapters: 1},
  {value: "Jonah", label: "Jonah",  numberOfChapters: 4},
  {value: "Micah", label: "Micah",  numberOfChapters: 7},
  {value: "Nahum", label: "Nahum",  numberOfChapters: 3},
  {value: "Habakkuk", label: "Habakkuk",  numberOfChapters: 3},
  {value: "Zephaniah", label: "Zephaniah",  numberOfChapters: 3},
  {value: "Haggai", label: "Haggai",  numberOfChapters: 2},
  {value: "Zechariah", label: "Zechariah",  numberOfChapters: 14},
  {value: "Malachi", label: "Malachi",  numberOfChapters: 4},
  {value: "Matthew", label: "Matthew",  numberOfChapters: 28},
  {value: "Mark", label: "Mark",  numberOfChapters: 16},
  {value: "Luke", label: "Luke",  numberOfChapters: 24},
  {value: "John", label: "John",  numberOfChapters: 21},
  {value: "Acts", label: "Acts",  numberOfChapters: 28},
  {value: "Romans", label: "Romans",  numberOfChapters: 16},
  {value: "1 Corinthians", label: "1 Corinthians",  numberOfChapters: 16},
  {value: "2 Corinthians", label: "2 Corinthians",  numberOfChapters: 13},
  {value: "Galatians", label: "Galatians",  numberOfChapters: 6},
  {value: "Ephesians", label: "Ephesians",  numberOfChapters: 6},
  {value: "Philippians", label: "Philippians",  numberOfChapters: 4},
  {value: "Colossians", label: "Colossians",  numberOfChapters: 4},
  {value: "1 Thessalonians", label: "1 Thessalonians",  numberOfChapters: 5},
  {value: "2 Thessalonians", label: "2 Thessalonians",  numberOfChapters: 3},
  {value: "1 Timothy", label: "1 Timothy",  numberOfChapters: 6},
  {value: "2 Timothy", label: "2 Timothy",  numberOfChapters: 4},
  {value: "Titus", label: "Titus",  numberOfChapters: 3},
  {value: "Philemon", label: "Philemon",  numberOfChapters: 1},
  {value: "Hebrews", label: "Hebrews",  numberOfChapters: 13},
  {value: "James", label: "James",  numberOfChapters: 5},
  {value: "1 Peter", label: "1 Peter",  numberOfChapters: 5},
  {value: "2 Peter", label: "2 Peter",  numberOfChapters: 3},
  {value: "1 John", label: "1 John",  numberOfChapters: 5},
  {value: "2 John", label: "2 John",  numberOfChapters: 1},
  {value: "3 John", label: "3 John",  numberOfChapters: 1},
  {value: "Jude", label: "Jude",  numberOfChapters: 1},
  {value: "Revelation", label: "Revelation",  numberOfChapters: 22},
];